# Collector specific configuration
config_url: "https://raw.githubusercontent.com/OCHA-DAP/hapi-pipelines/refs/heads/main/src/hapi/pipelines/configs/operational_presence.yaml"

resource_index_exceptions:
  afg: 2
  lbn: 1
